In [2]:
from pathlib import Path
import pandas as pd

# Project root
PROJECT_ROOT = Path(r"C:\Users\suriy\Desktop\healthcare_fraud")

# Feature importance file
importance_path = (
    PROJECT_ROOT
    / "experiments"
    / "outputs"
    / "feature_importance_300.csv"
)

print("Current notebook directory:")
print(Path.cwd())

print("\nLooking for:")
print(importance_path)

print("\nFile exists:", importance_path.exists())

# Load the feature importance results
importance_df = pd.read_csv(importance_path)

print("\nTotal features:", len(importance_df))

importance_df.head(20)

Current notebook directory:
c:\Users\suriy\Desktop\healthcare_fraud\experiments

Looking for:
C:\Users\suriy\Desktop\healthcare_fraud\experiments\outputs\feature_importance_300.csv

File exists: True

Total features: 300

    Rank                                       Feature  Importance
0      1                     count_ClaimID_perProvider   12.506232
1      2   count_ClaimID_perProviderClmProcedureCode_4    8.578028
2      3   count_ClaimID_perProviderClmProcedureCode_3    7.905803
3      4                mean_Hospital_Days_perProvider    6.504666
4      5            mean_DeductibleAmtPaid_perProvider    5.866651
5      6     mean_IPAnnualReimbursementAmt_perProvider    5.437650
6      7   count_ClaimID_perProviderClmProcedureCode_5    5.355179
7      8                   mean_Claim_Days_perProvider    5.215276
8      9       mean_InscClaimAmtReimbursed_perProvider    5.074442
9     10                          mean_Age_perProvider    4.591569
10    11        mean_OPAnnualDeductibleAmt_perProvider    4.467486
11    12        mean_IPAnnualDeductibleAmt_perProvider    3.840795
12    13  count_ClaimID_perProviderClmDiagnosisCode_10    3.152263
13    14                         mean_Risk_perProvider    2.894151
14    15   count_ClaimID_perProviderClmProcedureCode_2    2.643970
15    16     mean_OPAnnualReimbursementAmt_perProvider    2.557364
16    17   count_ClaimID_perProviderAttendingPhysician    1.187818
17    18   count_ClaimID_perProviderClmProcedureCode_1    1.069199
18    19   count_ClaimID_perProviderDiagnosisGroupCode    1.065652
19    20                       ChronicCond_Alzheimer_1    1.003228

In [3]:
pd.set_option("display.max_rows", 300)
pd.set_option("display.max_colwidth", 100)

importance_df

,Rank,Feature,Importance
0,1,count_ClaimID_perProvider,1.250623e+01
1,2,count_ClaimID_perProviderClmProcedureCode_4,8.578028e+00
2,3,count_ClaimID_perProviderClmProcedureCode_3,7.905803e+00
3,4,mean_Hospital_Days_perProvider,6.504666e+00
4,5,mean_DeductibleAmtPaid_perProvider,5.866651e+00
5,6,mean_IPAnnualReimbursementAmt_perProvider,5.437650e+00
6,7,count_ClaimID_perProviderClmProcedureCode_5,5.355179e+00
7,8,mean_Claim_Days_perProvider,5.215276e+00
8,9,mean_InscClaimAmtReimbursed_perProvider,5.074442e+00
9,10,mean_Age_perProvider,4.591569e+00
10,11,mean_OPAnnualDeductibleAmt_perProvider,4.467486e+00
11,12,mean_IPAnnualDeductibleAmt_perProvider,3.840795e+00
12,13,count_ClaimID_perProviderClmDiagnosisCode_10,3.152263e+00
13,14,mean_Risk_perProvider,2.894151e+00
14,15,count_ClaimID_perProviderClmProcedureCode_2,2.643970e+00
15,16,mean_OPAnnualReimbursementAmt_perProvider,2.557364e+00
16,17,count_ClaimID_perProviderAttendingPhysician,1.187818e+00
17,18,count_ClaimID_perProviderClmProcedureCode_1,1.069199e+00
18,19,count_ClaimID_perProviderDiagnosisGroupCode,1.065652e+00
19,20,ChronicCond_Alzheimer_1,1.003228e+00
20,21,Age_Category_Old,9.996495e-01
21,22,Gender_1,7.596015e-01
22,23,ChronicCond_Osteoporasis_0,7.502675e-01
23,24,ChronicCond_rheumatoidarthritis_0,7.279014e-01
24,25,Gender_0,7.169635e-01
25,26,ChronicCond_Alzheimer_0,7.102525e-01
26,27,ChronicCond_rheumatoidarthritis_1,5.609242e-01
27,28,ChronicCond_Depression_1,5.437540e-01
28,29,ChronicCond_Heartfailure_0,4.504228e-01
29,30,ChronicCond_Diabetes_1,3.896047e-01
30,31,ChronicCond_Diabetes_0,3.724580e-01
31,32,ChronicCond_Osteoporasis_1,3.366245e-01
32,33,ChronicCond_Heartfailure_1,2.765643e-01
33,34,ChronicCond_KidneyDisease_0,2.152016e-01
34,35,ChronicCond_Depression_0,2.084236e-01
35,36,count_ClaimID_perProviderClmDiagnosisCode_8,1.747747e-01
36,37,count_ClaimID_perProviderBeneID,1.636896e-01
37,38,count_ClaimID_perProviderClmDiagnosisCode_9,1.569172e-01
38,39,ChronicCond_ObstrPulmonary_0,1.391169e-01
39,40,ChronicCond_IschemicHeart_0,9.185870e-02
40,41,ChronicCond_IschemicHeart_1,7.270805e-02
41,42,count_ClaimID_perProviderClmDiagnosisCode_7,6.293017e-02
42,43,count_ClaimID_perProviderClmDiagnosisCode_4,4.847336e-02
43,44,count_ClaimID_perProviderClmDiagnosisCode_5,4.316171e-02
44,45,count_ClaimID_perProviderOtherPhysician,2.510054e-02
45,46,count_ClaimID_perProviderOperatingPhysician,2.358628e-02
46,47,count_ClaimID_perProviderClmDiagnosisCode_6,1.974502e-02
47,48,mean_DeductibleAmtPaid_perAttendingPhysician,1.425335e-02
48,49,mean_IPAnnualDeductibleAmt_perAttendingPhysician,6.894983e-03
49,50,mean_InscClaimAmtReimbursed_perAttendingPhysician,6.643325e-03
50,51,mean_Hospital_Days_perAttendingPhysician,6.060240e-03
51,52,mean_Claim_Days_perBeneID,5.509229e-03
52,53,mean_IPAnnualReimbursementAmt_perAttendingPhysician,1.124323e-03
53,54,mean_Hospital_Days_perClmDiagnosisCode_1,1.034106e-03
54,55,mean_Claim_Days_perAttendingPhysician,2.268922e-04
55,56,mean_Risk_perClmProcedureCode_4,1.070484e-04
56,57,mean_Hospital_Days_perClmProcedureCode_4,3.690665e-05
57,58,mean_Hospital_Days_perClmProcedureCode_5,4.733095e-06
58,59,mean_InscClaimAmtReimbursed_perClmProcedureCode_5,3.095677e-06
59,60,mean_IPAnnualReimbursementAmt_perClmProcedureCode_5,2.119528e-06
60,61,mean_OPAnnualDeductibleAmt_perClmProcedureCode_5,1.414171e-06
61,62,mean_Claim_Days_perClmProcedureCode_5,7.125677e-07
62,63,mean_Risk_perOperatingPhysician,0.000000e+00
63,64,mean_InscClaimAmtReimbursed_perOtherPhysician,0.000000e+00
64,65,mean_DeductibleAmtPaid_perOtherPhysician,0.000000e+00
65,66,mean_IPAnnualReimbursementAmt_perOtherPhysician,0.000000e+00
66,67,mean_IPAnnualDeductibleAmt_perOtherPhysician,0.000000e+00
67,68,mean_OPAnnualReimbursementAmt_perOtherPhysician,0.000000e+00
68,69,mean_OPAnnualDeductibleAmt_perOtherPhysician,0.000000e+00
69,70,mean_Age_perOtherPhysician,0.000000e+00
70,71,mean_Hospital_Days_perOtherPhysician,0.000000e+00
71,72,mean_Claim_Days_perOtherPhysician,0.000000e+00
72,73,mean_Risk_perOtherPhysician,0.000000e+00
73,74,mean_InscClaimAmtReimbursed_perDiagnosisGroupCode,0.000000e+00
74,75,mean_DeductibleAmtPaid_perDiagnosisGroupCode,0.000000e+00
75,76,mean_IPAnnualReimbursementAmt_perDiagnosisGroupCode,0.000000e+00
76,77,mean_IPAnnualDeductibleAmt_perDiagnosisGroupCode,0.000000e+00
77,78,mean_OPAnnualReimbursementAmt_perDiagnosisGroupCode,0.000000e+00
78,79,mean_OPAnnualDeductibleAmt_perDiagnosisGroupCode,0.000000e+00
79,80,mean_Age_perDiagnosisGroupCode,0.000000e+00
80,81,mean_Hospital_Days_perDiagnosisGroupCode,0.000000e+00
81,82,mean_Claim_Days_perDiagnosisGroupCode,0.000000e+00
82,83,mean_Risk_perDiagnosisGroupCode,0.000000e+00
83,84,mean_InscClaimAmtReimbursed_perClmAdmitDiagnosisCode,0.000000e+00
84,85,mean_DeductibleAmtPaid_perClmAdmitDiagnosisCode,0.000000e+00
85,86,mean_IPAnnualReimbursementAmt_perClmAdmitDiagnosisCode,0.000000e+00
86,87,mean_IPAnnualDeductibleAmt_perClmAdmitDiagnosisCode,0.000000e+00
87,88,mean_OPAnnualReimbursementAmt_perClmAdmitDiagnosisCode,0.000000e+00
88,89,mean_OPAnnualDeductibleAmt_perClmAdmitDiagnosisCode,0.000000e+00
89,90,mean_Age_perClmAdmitDiagnosisCode,0.000000e+00
90,91,mean_Hospital_Days_perClmAdmitDiagnosisCode,0.000000e+00
91,92,mean_Claim_Days_perClmAdmitDiagnosisCode,0.000000e+00
92,93,mean_Risk_perClmAdmitDiagnosisCode,0.000000e+00
93,94,mean_InscClaimAmtReimbursed_perClmProcedureCode_1,0.000000e+00
94,95,mean_DeductibleAmtPaid_perClmProcedureCode_1,0.000000e+00
95,96,mean_IPAnnualReimbursementAmt_perClmProcedureCode_1,0.000000e+00
96,97,mean_IPAnnualDeductibleAmt_perClmProcedureCode_1,0.000000e+00
97,98,mean_OPAnnualReimbursementAmt_perClmProcedureCode_1,0.000000e+00
98,99,mean_OPAnnualDeductibleAmt_perClmProcedureCode_1,0.000000e+00
99,100,mean_Age_perClmProcedureCode_1,0.000000e+00
100,101,mean_Hospital_Days_perClmProcedureCode_1,0.000000e+00
101,102,mean_Claim_Days_perClmProcedureCode_1,0.000000e+00
102,103,mean_Risk_perClmProcedureCode_1,0.000000e+00
103,104,mean_InscClaimAmtReimbursed_perClmProcedureCode_2,0.000000e+00
104,105,mean_DeductibleAmtPaid_perClmProcedureCode_2,0.000000e+00
105,106,mean_IPAnnualReimbursementAmt_perClmProcedureCode_2,0.000000e+00
106,107,mean_IPAnnualDeductibleAmt_perClmProcedureCode_2,0.000000e+00
107,108,mean_OPAnnualReimbursementAmt_perClmProcedureCode_2,0.000000e+00
108,109,mean_OPAnnualDeductibleAmt_perClmProcedureCode_2,0.000000e+00
109,110,mean_Age_perClmProcedureCode_2,0.000000e+00
110,111,mean_Hospital_Days_perClmProcedureCode_2,0.000000e+00
111,112,mean_Claim_Days_perClmProcedureCode_2,0.000000e+00
112,113,mean_Risk_perClmProcedureCode_2,0.000000e+00
113,114,mean_InscClaimAmtReimbursed_perClmProcedureCode_3,0.000000e+00
114,115,mean_DeductibleAmtPaid_perClmProcedureCode_3,0.000000e+00
115,116,mean_IPAnnualReimbursementAmt_perClmProcedureCode_3,0.000000e+00
116,117,mean_IPAnnualDeductibleAmt_perClmProcedureCode_3,0.000000e+00
117,118,mean_OPAnnualReimbursementAmt_perClmProcedureCode_3,0.000000e+00
118,119,mean_OPAnnualDeductibleAmt_perClmProcedureCode_3,0.000000e+00
119,120,mean_Age_perClmProcedureCode_3,0.000000e+00
120,121,mean_Hospital_Days_perClmProcedureCode_3,0.000000e+00
121,122,mean_Claim_Days_perClmProcedureCode_3,0.000000e+00
122,123,mean_Risk_perClmProcedureCode_3,0.000000e+00
123,124,mean_InscClaimAmtReimbursed_perClmProcedureCode_4,0.000000e+00
124,125,mean_DeductibleAmtPaid_perClmProcedureCode_4,0.000000e+00
125,126,mean_IPAnnualReimbursementAmt_perClmProcedureCode_4,0.000000e+00
126,127,mean_IPAnnualDeductibleAmt_perClmProcedureCode_4,0.000000e+00
127,128,mean_OPAnnualReimbursementAmt_perClmProcedureCode_4,0.000000e+00
128,129,mean_OPAnnualDeductibleAmt_perClmProcedureCode_4,0.000000e+00
129,130,mean_Age_perClmProcedureCode_4,0.000000e+00
130,131,mean_Claim_Days_perClmProcedureCode_4,0.000000e+00
131,132,mean_DeductibleAmtPaid_perClmProcedureCode_5,0.000000e+00
132,133,mean_IPAnnualDeductibleAmt_perClmProcedureCode_5,0.000000e+00
133,134,mean_OPAnnualReimbursementAmt_perClmProcedureCode_5,0.000000e+00
134,135,mean_Age_perClmProcedureCode_5,0.000000e+00
135,136,mean_Risk_perClmProcedureCode_5,0.000000e+00
136,137,mean_InscClaimAmtReimbursed_perClmProcedureCode_6,0.000000e+00
137,138,mean_DeductibleAmtPaid_perClmProcedureCode_6,0.000000e+00
138,139,mean_IPAnnualReimbursementAmt_perClmProcedureCode_6,0.000000e+00
139,140,mean_IPAnnualDeductibleAmt_perClmProcedureCode_6,0.000000e+00
140,141,mean_OPAnnualReimbursementAmt_perClmProcedureCode_6,0.000000e+00
141,142,mean_OPAnnualDeductibleAmt_perClmProcedureCode_6,0.000000e+00
142,143,mean_Age_perClmProcedureCode_6,0.000000e+00
143,144,mean_Hospital_Days_perClmProcedureCode_6,0.000000e+00
144,145,mean_Claim_Days_perClmProcedureCode_6,0.000000e+00
145,146,mean_Risk_perClmProcedureCode_6,0.000000e+00
146,147,mean_InscClaimAmtReimbursed_perClmDiagnosisCode_1,0.000000e+00
147,148,mean_DeductibleAmtPaid_perClmDiagnosisCode_1,0.000000e+00
148,149,mean_IPAnnualReimbursementAmt_perClmDiagnosisCode_1,0.000000e+00
149,150,mean_IPAnnualDeductibleAmt_perClmDiagnosisCode_1,0.000000e+00
150,151,mean_OPAnnualReimbursementAmt_perClmDiagnosisCode_1,0.000000e+00
151,152,mean_OPAnnualDeductibleAmt_perClmDiagnosisCode_1,0.000000e+00
152,153,mean_Age_perClmDiagnosisCode_1,0.000000e+00
153,154,RenalDiseaseIndicator,0.000000e+00
154,155,mean_Claim_Days_perClmDiagnosisCode_1,0.000000e+00
155,156,mean_Risk_perClmDiagnosisCode_1,0.000000e+00
156,157,mean_InscClaimAmtReimbursed_perClmDiagnosisCode_2,0.000000e+00
157,158,mean_DeductibleAmtPaid_perClmDiagnosisCode_2,0.000000e+00
158,159,mean_IPAnnualReimbursementAmt_perClmDiagnosisCode_2,0.000000e+00
159,160,mean_IPAnnualDeductibleAmt_perClmDiagnosisCode_2,0.000000e+00
160,161,mean_OPAnnualReimbursementAmt_perClmDiagnosisCode_2,0.000000e+00
161,162,mean_OPAnnualDeductibleAmt_perClmDiagnosisCode_2,0.000000e+00
162,163,mean_Age_perClmDiagnosisCode_2,0.000000e+00
163,164,mean_Hospital_Days_perClmDiagnosisCode_2,0.000000e+00
164,165,mean_Claim_Days_perClmDiagnosisCode_2,0.000000e+00
165,166,mean_Risk_perClmDiagnosisCode_2,0.000000e+00
166,167,mean_InscClaimAmtReimbursed_perClmDiagnosisCode_3,0.000000e+00
167,168,mean_DeductibleAmtPaid_perClmDiagnosisCode_3,0.000000e+00
168,169,mean_IPAnnualReimbursementAmt_perClmDiagnosisCode_3,0.000000e+00
169,170,mean_IPAnnualDeductibleAmt_perClmDiagnosisCode_3,0.000000e+00
170,171,mean_OPAnnualReimbursementAmt_perClmDiagnosisCode_3,0.000000e+00
171,172,mean_OPAnnualDeductibleAmt_perClmDiagnosisCode_3,0.000000e+00
172,173,mean_Age_perClmDiagnosisCode_3,0.000000e+00
173,174,mean_Hospital_Days_perClmDiagnosisCode_3,0.000000e+00
174,175,mean_Claim_Days_perClmDiagnosisCode_3,0.000000e+00
175,176,mean_Risk_perClmDiagnosisCode_3,0.000000e+00
176,177,mean_InscClaimAmtReimbursed_perClmDiagnosisCode_4,0.000000e+00
177,178,mean_DeductibleAmtPaid_perClmDiagnosisCode_4,0.000000e+00
178,179,mean_IPAnnualReimbursementAmt_perClmDiagnosisCode_4,0.000000e+00
179,180,mean_IPAnnualDeductibleAmt_perClmDiagnosisCode_4,0.000000e+00
180,181,mean_OPAnnualReimbursementAmt_perClmDiagnosisCode_4,0.000000e+00
181,182,mean_OPAnnualDeductibleAmt_perClmDiagnosisCode_4,0.000000e+00
182,183,mean_Age_perClmDiagnosisCode_4,0.000000e+00
183,184,mean_Hospital_Days_perClmDiagnosisCode_4,0.000000e+00
184,185,mean_Claim_Days_perClmDiagnosisCode_4,0.000000e+00
185,186,mean_Risk_perClmDiagnosisCode_4,0.000000e+00
186,187,mean_InscClaimAmtReimbursed_perClmDiagnosisCode_5,0.000000e+00
187,188,mean_DeductibleAmtPaid_perClmDiagnosisCode_5,0.000000e+00
188,189,mean_IPAnnualReimbursementAmt_perClmDiagnosisCode_5,0.000000e+00
189,190,mean_IPAnnualDeductibleAmt_perClmDiagnosisCode_5,0.000000e+00
190,191,mean_OPAnnualReimbursementAmt_perClmDiagnosisCode_5,0.000000e+00
191,192,mean_OPAnnualDeductibleAmt_perClmDiagnosisCode_5,0.000000e+00
192,193,mean_Age_perClmDiagnosisCode_5,0.000000e+00
193,194,mean_Hospital_Days_perClmDiagnosisCode_5,0.000000e+00
194,195,mean_Claim_Days_perClmDiagnosisCode_5,0.000000e+00
195,196,mean_Risk_perClmDiagnosisCode_5,0.000000e+00
196,197,mean_InscClaimAmtReimbursed_perClmDiagnosisCode_6,0.000000e+00
197,198,mean_DeductibleAmtPaid_perClmDiagnosisCode_6,0.000000e+00
198,199,mean_IPAnnualReimbursementAmt_perClmDiagnosisCode_6,0.000000e+00
199,200,mean_IPAnnualDeductibleAmt_perClmDiagnosisCode_6,0.000000e+00
200,201,mean_OPAnnualReimbursementAmt_perClmDiagnosisCode_6,0.000000e+00
201,202,mean_OPAnnualDeductibleAmt_perClmDiagnosisCode_6,0.000000e+00
202,203,mean_Age_perClmDiagnosisCode_6,0.000000e+00
203,204,mean_Hospital_Days_perClmDiagnosisCode_6,0.000000e+00
204,205,mean_Claim_Days_perClmDiagnosisCode_6,0.000000e+00
205,206,mean_Risk_perClmDiagnosisCode_6,0.000000e+00
206,207,mean_InscClaimAmtReimbursed_perClmDiagnosisCode_7,0.000000e+00
207,208,mean_DeductibleAmtPaid_perClmDiagnosisCode_7,0.000000e+00
208,209,mean_IPAnnualReimbursementAmt_perClmDiagnosisCode_7,0.000000e+00
209,210,mean_IPAnnualDeductibleAmt_perClmDiagnosisCode_7,0.000000e+00
210,211,mean_OPAnnualReimbursementAmt_perClmDiagnosisCode_7,0.000000e+00
211,212,mean_OPAnnualDeductibleAmt_perClmDiagnosisCode_7,0.000000e+00
212,213,mean_Age_perClmDiagnosisCode_7,0.000000e+00
213,214,mean_Hospital_Days_perClmDiagnosisCode_7,0.000000e+00
214,215,mean_Claim_Days_perClmDiagnosisCode_7,0.000000e+00
215,216,mean_Risk_perClmDiagnosisCode_7,0.000000e+00
216,217,mean_InscClaimAmtReimbursed_perClmDiagnosisCode_8,0.000000e+00
217,218,mean_DeductibleAmtPaid_perClmDiagnosisCode_8,0.000000e+00
218,219,mean_IPAnnualReimbursementAmt_perClmDiagnosisCode_8,0.000000e+00
219,220,mean_IPAnnualDeductibleAmt_perClmDiagnosisCode_8,0.000000e+00
220,221,mean_OPAnnualReimbursementAmt_perClmDiagnosisCode_8,0.000000e+00
221,222,mean_OPAnnualDeductibleAmt_perClmDiagnosisCode_8,0.000000e+00
222,223,mean_Age_perClmDiagnosisCode_8,0.000000e+00
223,224,mean_Hospital_Days_perClmDiagnosisCode_8,0.000000e+00
224,225,mean_Claim_Days_perClmDiagnosisCode_8,0.000000e+00
225,226,NoOfMonths_PartACov,0.000000e+00
226,227,mean_InscClaimAmtReimbursed_perClmDiagnosisCode_9,0.000000e+00
227,228,mean_DeductibleAmtPaid_perClmDiagnosisCode_9,0.000000e+00
228,229,mean_IPAnnualReimbursementAmt_perClmDiagnosisCode_9,0.000000e+00
229,230,mean_IPAnnualDeductibleAmt_perClmDiagnosisCode_9,0.000000e+00
230,231,mean_OPAnnualReimbursementAmt_perClmDiagnosisCode_9,0.000000e+00
231,232,mean_OPAnnualDeductibleAmt_perClmDiagnosisCode_9,0.000000e+00
232,233,mean_Age_perClmDiagnosisCode_9,0.000000e+00
233,234,mean_Hospital_Days_perClmDiagnosisCode_9,0.000000e+00
234,235,mean_Claim_Days_perClmDiagnosisCode_9,0.000000e+00
235,236,mean_Risk_perClmDiagnosisCode_9,0.000000e+00
236,237,mean_InscClaimAmtReimbursed_perClmDiagnosisCode_10,0.000000e+00
237,238,mean_DeductibleAmtPaid_perClmDiagnosisCode_10,0.000000e+00
238,239,mean_IPAnnualReimbursementAmt_perClmDiagnosisCode_10,0.000000e+00
239,240,mean_IPAnnualDeductibleAmt_perClmDiagnosisCode_10,0.000000e+00
240,241,mean_OPAnnualReimbursementAmt_perClmDiagnosisCode_10,0.000000e+00
241,242,mean_OPAnnualDeductibleAmt_perClmDiagnosisCode_10,0.000000e+00
242,243,mean_Age_perClmDiagnosisCode_10,0.000000e+00
243,244,mean_Hospital_Days_perClmDiagnosisCode_10,0.000000e+00
244,245,mean_Claim_Days_perClmDiagnosisCode_10,0.000000e+00
245,246,mean_Risk_perClmDiagnosisCode_10,0.000000e+00
246,247,NoOfMonths_PartBCov,0.000000e+00
247,248,IPAnnualReimbursementAmt,0.000000e+00
248,249,IPAnnualDeductibleAmt,0.000000e+00
249,250,OPAnnualReimbursementAmt,0.000000e+00
250,251,OPAnnualDeductibleAmt,0.000000e+00
251,252,count_ClaimID_perProviderClmAdmitDiagnosisCode,0.000000e+00
252,253,Claim_Days,0.000000e+00
253,254,Hospital_Days,0.000000e+00
254,255,mean_DeductibleAmtPaid_perBeneID,0.000000e+00
255,256,InscClaimAmtReimbursed,0.000000e+00
256,257,ChronicCond_KidneyDisease_1,0.000000e+00
257,258,count_ClaimID_perProviderClmDiagnosisCode_1,0.000000e+00
258,259,count_ClaimID_perProviderClmDiagnosisCode_2,0.000000e+00
259,260,count_ClaimID_perProviderClmDiagnosisCode_3,0.000000e+00
260,261,ChronicCond_Cancer_0,0.000000e+00
261,262,ChronicCond_Cancer_1,0.000000e+00
262,263,mean_Risk_perClmDiagnosisCode_8,0.000000e+00
263,264,ChronicCond_ObstrPulmonary_1,0.000000e+00
264,265,mean_IPAnnualReimbursementAmt_perBeneID,0.000000e+00
265,266,mean_IPAnnualDeductibleAmt_perBeneID,0.000000e+00
266,267,mean_OPAnnualReimbursementAmt_perBeneID,0.000000e+00
267,268,mean_OPAnnualDeductibleAmt_perBeneID,0.000000e+00
268,269,mean_Age_perBeneID,0.000000e+00
269,270,mean_Hospital_Days_perBeneID,0.000000e+00
270,271,mean_Risk_perBeneID,0.000000e+00
271,272,IsHospitalized,0.000000e+00
272,273,ChronicCond_stroke_0,0.000000e+00
273,274,ChronicCond_stroke_1,0.000000e+00
274,275,Age_Category_Adult,0.000000e+00
275,276,mean_OPAnnualReimbursementAmt_perAttendingPhysician,0.000000e+00
276,277,Age_Category_Very Old,0.000000e+00
277,278,Age_Category_Young,0.000000e+00
278,279,mean_OPAnnualDeductibleAmt_perAttendingPhysician,0.000000e+00
279,280,mean_Age_perAttendingPhysician,0.000000e+00
280,281,Race_1,0.000000e+00
281,282,Race_2,0.000000e+00
282,283,Race_3,0.000000e+00
283,284,Race_5,0.000000e+00
284,285,Difference,0.000000e+00
285,286,IsAlive,0.000000e+00
286,287,Age,0.000000e+00
287,288,Risk,0.000000e+00
288,289,mean_Risk_perAttendingPhysician,0.000000e+00
289,290,mean_InscClaimAmtReimbursed_perOperatingPhysician,0.000000e+00
290,291,mean_DeductibleAmtPaid_perOperatingPhysician,0.000000e+00
291,292,mean_IPAnnualReimbursementAmt_perOperatingPhysician,0.000000e+00
292,293,mean_IPAnnualDeductibleAmt_perOperatingPhysician,0.000000e+00
293,294,mean_OPAnnualReimbursementAmt_perOperatingPhysician,0.000000e+00
294,295,mean_OPAnnualDeductibleAmt_perOperatingPhysician,0.000000e+00
295,296,mean_Age_perOperatingPhysician,0.000000e+00
296,297,mean_Hospital_Days_perOperatingPhysician,0.000000e+00
297,298,mean_Claim_Days_perOperatingPhysician,0.000000e+00
298,299,mean_InscClaimAmtReimbursed_perBeneID,0.000000e+00
299,300,DeductibleAmtPaid,0.000000e+00